version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db  # Volume nomeado p/ persistência dos dados

  fastapi:
    image: test2313123/quizverse
    container_name: fastapi
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017  # URI usada pelo app para conectar ao MongoDB
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  mongo_data:  # Volume persistente para o MongoDB
